import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import QueryProvider from "@/providers/QueryProvider";
import { ConfigProvider, App } from "antd";
import { auth } from "@/auth";
import UserHeader from "@/components/UserHeader";

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <QueryProvider>
          <ConfigProvider>
            <App>
              {/* Header hiển thị user info */}
              <UserHeader user={session?.user} />
              {children}
              {modal} {/* Render Modal Slot ở đây */}
            </App>
          </ConfigProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
